FROM gradle:8.5-jdk17 AS build

#définir le répertoire de travail
WORKDIR /app

#copier les fichiers de configuration gradle
COPY build.gradle settings.gradle ./

#copier les repertoires des wrappers gradle
COPY gradlew gradlew.bat ./
COPY gradle ./gradle

#copier les fichiers sources
COPY src ./src

#compiler l'application
RUN ./gradlew bootJar -x test --no-daemon --info

#ETAPE 2 : Exécution
FROM eclipse-temurin:21-jre-alpine

#copier le jar depuis le stage de build
COPY --from=build /app/build/libs/*.jar app.jar

#exposer le port
EXPOSE 9081

#demarrer l'application
ENTRYPOINT ["java", "-jar", "/app.jar"]



