spring.application.name=plateform

# Bean override configuration
spring.main.allow-bean-definition-overriding=true

# Configuration serveur
server.port=8081
server.servlet.context-path=/api

# Configuration Jackson
spring.jackson.serialization.fail-on-empty-beans=false
spring.jackson.default-property-inclusion=non_null

# Configuration JWT
jwt.jwtExpirationMs=86400000
jwt.jwtSecret=0b65fa636af7aa3cb256886e744af046e57d735f2deef8fedd29f75b297cf08d6928b25ebd2b85cfe9535682291ef9e050f5b5b4236def8e4ebf860f9c9ef542

# Configuration Swagger/OpenAPI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.show-actuator=true
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.tryItOutEnabled=true

# Profil actif par d�faut
spring.profiles.active=dev